AllCops:
  Exclude:
    - DerivedData/**/*
    - Pods/**/*
    - vendor/**/*
  # Opt in to new cops by default
  NewCops: enable

# Allow the Podspec filename to match the project
Naming/FileName:
  Exclude:
    - 'WordPressAuthenticator.podspec'

Metrics/BlockLength:
  Exclude:
    - 'WordPressAuthenticator.podspec'

# Override the maximum line length
Layout/LineLength:
  Max: 160
