# Nodes with values to reuse in the pipeline.
common_params:
  plugins: &common_plugins
  - automattic/bash-cache#2.12.0
  env: &common_env
    IMAGE_ID: xcode-14.1

# This is the default pipeline – it will build and test the pod
steps:
  #################
  # Build and Test
  #################
  - label: "🧪 Build and Test"
    key: "test"
    command: .buildkite/build-and-test.sh
    env: *common_env
    plugins: *common_plugins

  - label: ":calling: Build Demo App"
    key: "build-demo-app"
    command: .buildkite/build-demo-app.sh
    env: *common_env
    plugins: *common_plugins

  #################
  # Validate Podspec
  #################
  - label: "🔬 Validate Podspec"
    key: "validate"
    command: |
      validate_podspec
    env: *common_env
    plugins: *common_plugins

  #################
  # Lint
  #################
  - label: "🧹 Lint Pod"
    key: "lint"
    command: |
      lint_pod
    env: *common_env
    plugins: *common_plugins

  - label: ":rubocop: Lint Ruby Tooling"
    command: .buildkite/rubocop-via-danger.sh
    plugins: *common_plugins
    agents:
      # We only need Ruby for this step; using the android queue is cheaper
      # than the macOS one.
      queue: android

  #################
  # Publish the Podspec (if we're building a tag)
  #################
  - label: "⬆️ Publish Podspec"
    key: "publish"
    command: .buildkite/publish-pod.sh
    env: *common_env
    plugins: *common_plugins
    depends_on:
      - "test"
      - "validate"
      - "lint"
      - "build-demo-app"
    if: build.tag != null
    agents:
      queue: "mac"
