# frozen_string_literal: true

default_platform(:ios)

BUILD_DIR = File.join(__dir__, '.build')
BUILD_LOG_PATH = File.join(BUILD_DIR, 'logs')
DERIVED_DATA_PATH = File.join(BUILD_DIR, 'derived-data')

platform :ios do
  desc 'Builds the project and runs tests'
  lane :test do
    run_tests(
      # Usually, a framework's scheme has the same name as the framework.
      # However, the CocoaPods setup in this project results in two schemes
      # named WordPressAuthenticator being created, one in the
      # WordPressAuthenticator.xcodeproj and the other in Pods.xcodeproj. This
      # can result in ambiguity when running the tests from Fastlane over which
      # scheme to use. To avoid the issue, we renamed the desired scheme to
      # "Framework".
      scheme: 'Framework',
      prelaunch_simulator: true,
      buildlog_path: BUILD_LOG_PATH,
      derived_data_path: DERIVED_DATA_PATH
    )
  end

  desc 'Run UI tests on the demo app'
  lane :ui_test_demo_app do
    run_tests(
      scheme: 'UITests',
      prelaunch_simulator: true,
      buildlog_path: BUILD_LOG_PATH,
      derived_data_path: DERIVED_DATA_PATH,
      result_bundle: true,
      device: 'iPhone 14'
    )
  end

  lane :build_demo_app do
    build_app(
      scheme: 'AuthenticatorDemo',
      # Skip archiving and code signing, this is just a smoke test to make
      # sure the integration between framework and demo app works
      skip_archive: true,
      skip_codesigning: true,
      buildlog_path: BUILD_LOG_PATH,
      derived_data_path: DERIVED_DATA_PATH
    )
  end
end
