# frozen_string_literal: true

default_platform(:ios)

BUILD_DIR = File.join(__dir__, '.build')
BUILD_LOG_PATH = File.join(BUILD_DIR, 'logs')
DERIVED_DATA_PATH = File.join(BUILD_DIR, 'derived-data')

platform :ios do
  desc 'Builds the project and runs tests'
  lane :test do
    run_tests(
      scheme: 'WordPressAuthenticator',
      prelaunch_simulator: true,
      buildlog_path: BUILD_LOG_PATH,
      derived_data_path: DERIVED_DATA_PATH
    )
  end
end
