# frozen_string_literal: true

default_platform(:ios)

BUILD_DIR = File.join(__dir__, '.build')
BUILD_LOG_PATH = File.join(BUILD_DIR, 'logs')
DERIVED_DATA_PATH = File.join(BUILD_DIR, 'derived-data')

platform :ios do
  desc 'Builds the project and runs tests'
  lane :test do
    run_tests(
      scheme: 'WordPressAuthenticator',
      prelaunch_simulator: true,
      buildlog_path: BUILD_LOG_PATH,
      derived_data_path: DERIVED_DATA_PATH
    )
  end

  lane :build_demo_app do
    build_app(
      scheme: 'AuthenticatorDemo',
      # Skip archiving and code signing, this is just a smoke test to make
      # sure the integration between framework and demo app works
      skip_archive: true,
      skip_codesigning: true,
      buildlog_path: BUILD_LOG_PATH,
      derived_data_path: DERIVED_DATA_PATH
    )
  end
end
